repos:
  - repo: 'https://github.com/pre-commit/pre-commit-hooks'
    rev: v2.4.0
    hooks:
      # проверяет наличие переноса строки в конце всех текстовых файлов
      - id: end-of-file-fixer
      # предупреждает о добавлении больших файлов в Git
      - id: check-added-large-files
      # предупреждает о сохранении файлов с UTF-8 BOM
      - id: check-byte-order-marker
      # предотвращает сохранение приватных ключей
      - id: detect-private-key
      # проверяет, что файлы, которые мы собираемся сохранять, как минимум валидный Python
      - id: check-ast
  - repo: 'https://github.com/pycqa/flake8'
    rev: '6.1.0'
    hooks:
      - id: flake8
        args: [
          "--ignore=E203,E501,W503,F401,FI10,FI11,FI12,FI13,FI14,FI15,FI16,FI17,FI58,PT013",
          # black
          # E203 whitespace before ':'
          # W503 line break before binary operator
          # flake8-future-import
          # FI10 future import "division" missing
          # FI11 future import "absolute_import" missing
          # FI12 future import "with_statement" missing
          # FI13 future import "print_function" missing
          # FI14 future import "unicode_literals" missing
          # FI15 future import "generator_stop" missing
          # FI16 future import "nested_scopes" missing
          # FI17 future import "generators" missing
          # FI58 future import "annotations" present
          # flake8-pytest-style
          # PT013 found incorrect import of pytest, use simple 'import pytest' instead
          "--max-line-length=110",
          "--per-file-ignores=tests/*.py:S101"
          # S101 Use of assert detected
        ]
        additional_dependencies:
          - flake8-bugbear
          - flake8-comprehensions
          - flake8-simplify
        exclude: ^src/blib2to3/
  - repo: 'https://github.com/psf/black'
    rev: '23.9.1'
    hooks:
      - id: black
  - repo: 'https://github.com/pycqa/isort'
    rev: '5.12.0'
    hooks:
      - id: isort
        args: ["--profile", "black", "--filter-files"]
