# Generated by Django 5.0.6 on 2024-05-28 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Specialization",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=50)),
            ],
            options={
                "verbose_name": "Специализации",
                "verbose_name_plural": "Специализации",
                "ordering": ["id"],
            },
        ),
    ]
