# Generated by Django 5.0.6 on 2024-05-30 13:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0004_add_topic_model"),
    ]

    operations = [
        migrations.CreateModel(
            name="Image",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.ImageField(upload_to="", verbose_name="Файл")),
            ],
            options={
                "verbose_name": "Фото",
                "verbose_name_plural": "Фото",
            },
        ),
        migrations.AlterField(
            model_name="group",
            name="date_formation",
            field=models.DateField(
                default=datetime.datetime(
                    2024, 5, 30, 13, 43, 37, 477831, tzinfo=datetime.timezone.utc
                ),
                verbose_name="Дата образования",
            ),
        ),
    ]
