# Generated by Django 5.0.6 on 2024-05-30 13:43

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0005_add_image_model"),
    ]

    operations = [
        migrations.AlterField(
            model_name="group",
            name="date_formation",
            field=models.DateField(
                default=datetime.datetime(
                    2024, 5, 30, 13, 43, 46, 182542, tzinfo=datetime.timezone.utc
                ),
                verbose_name="Дата образования",
            ),
        ),
        migrations.CreateModel(
            name="Test",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=50, verbose_name="Название")),
                (
                    "images",
                    models.ManyToManyField(
                        blank=True, to="courses.image", verbose_name="Фото"
                    ),
                ),
                (
                    "topic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="courses.topic",
                        verbose_name="Тема",
                    ),
                ),
            ],
            options={
                "verbose_name": "Тест",
                "verbose_name_plural": "Тесты",
            },
        ),
    ]
