# Generated by Django 5.0.6 on 2024-05-30 13:43

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0006_add_test_model"),
    ]

    operations = [
        migrations.AlterField(
            model_name="group",
            name="date_formation",
            field=models.DateField(
                default=datetime.datetime(
                    2024, 5, 30, 13, 43, 56, 726171, tzinfo=datetime.timezone.utc
                ),
                verbose_name="Дата образования",
            ),
        ),
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField(verbose_name="Текст вопроса")),
                (
                    "difficulty",
                    models.CharField(
                        choices=[
                            ("Easy", "Easy"),
                            ("Medium", "Medium"),
                            ("Hard", "Hard"),
                        ],
                        max_length=6,
                        verbose_name="Сложность",
                    ),
                ),
                (
                    "test",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="courses.test",
                        verbose_name="Тест",
                    ),
                ),
            ],
            options={
                "verbose_name": "Вопрос",
                "verbose_name_plural": "Вопросы",
            },
        ),
    ]
