# Generated by Django 5.0.6 on 2024-05-30 13:44

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0007_add_question_model"),
    ]

    operations = [
        migrations.AlterField(
            model_name="group",
            name="date_formation",
            field=models.DateField(
                default=datetime.datetime(
                    2024, 5, 30, 13, 44, 9, 59783, tzinfo=datetime.timezone.utc
                ),
                verbose_name="Дата образования",
            ),
        ),
        migrations.CreateModel(
            name="Answer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100, verbose_name="Ответ")),
                ("is_correct", models.BooleanField(verbose_name="Верный ответ")),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="courses.question",
                        verbose_name="Вопрос",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ответ",
                "verbose_name_plural": "Ответы",
            },
        ),
    ]
