# Generated by Django 5.0.6 on 2024-05-30 13:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0010_add_complited_test_model"),
    ]

    operations = [
        migrations.AlterField(
            model_name="group",
            name="date_formation",
            field=models.DateField(
                default=datetime.datetime(
                    2024, 5, 30, 13, 45, 43, 505068, tzinfo=datetime.timezone.utc
                ),
                verbose_name="Дата образования",
            ),
        ),
    ]
