# Generated by Django 5.0.6 on 2024-06-12 12:03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0011_answer_created_at_answer_updated_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="group",
            name="date_formation",
            field=models.DateField(
                default=django.utils.timezone.now, verbose_name="Дата образования"
            ),
        ),
    ]
