# Generated by Django 5.0.6 on 2024-06-20 06:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0012_alter_group_date_formation"),
        ("users", "0006_customuser_email_is_verified"),
    ]

    operations = [
        migrations.AlterField(
            model_name="group",
            name="students",
            field=models.ManyToManyField(
                related_name="groups", to="users.student", verbose_name="Студенты"
            ),
        ),
    ]
