# Generated by Django 5.0.6 on 2024-05-28 09:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0001_add_specialization_model"),
        ("users", "0002_add_student_model"),
    ]

    operations = [
        migrations.CreateModel(
            name="Teacher",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "specializations",
                    models.ManyToManyField(
                        to="courses.specialization", verbose_name="Специализации"
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Преподаватели",
                "verbose_name_plural": "Преподаватели",
                "ordering": ["id"],
            },
        ),
    ]
